# Created by: Tomoyuki Sakurai <y@trombik.org>
# $FreeBSD$

MAINTAINER=	y@trombik.org
MASTERDIR=	${.CURDIR}/../u-boot-master

MODEL=		orangepi-lite
BOARD_CONFIG=	orangepi_lite_defconfig
FAMILY=		allwinner

.include "${MASTERDIR}/Makefile"
