# Created by: Tomoyuki Sakurai <y@trombik.org>
# $FreeBSD$

PORTNAME=	libCharon
PORTVERSION=	4.0.0
CATEGORIES=	devel python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	y@trombik.org
COMMENT=	Read 3D-printing related file formats

LICENSE=	LGPL3
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=	python:3.5+
USE_PYTHON=	distutils flavors autoplist
USE_GITHUB=	yes
GH_ACCOUNT=	Ultimaker

.include <bsd.port.mk>
