# Created by: Tomoyuki Sakurai <y@trombik.org>
# $FreeBSD$

PORTNAME=	avl_tree
PORTVERSION=	1.2.1
CATEGORIES=	devel rubygems
MASTER_SITES=	RG

MAINTAINER=	y@trombik.org
COMMENT=	AVL tree, Red-black tree and Lock-free Red black tree in Ruby

LICENSE=	RUBY BSD2CLAUSE
LICENSE_COMB= dual

RUN_DEPENDS= devel/rubygem-atomic>=1.1:devel/rubygem-atomic

NO_ARCH=	yes
USES=		gem
USE_RUBY=	yes

.include <bsd.port.mk>
