# Created by: Tomoyuki Sakurai <y@trombik.org>
# $FreeBSD$

PORTNAME=	CuraEngine
PORTVERSION=	3.0.3
CATEGORIES=	cad

MAINTAINER=	y@trombik.org
COMMENT=	C++ console application for 3D printing GCode generation

LICENSE=	AGPLv3
LICENSE_FILE=	${WRKSRC}/LICENSE

LIB_DEPENDS=	libArcus.so:devel/libArcus

USES=	cmake
USE_GITHUB=	yes
GH_ACCOUNT= Ultimaker
PLIST_FILES=	bin/CuraEngine

.include <bsd.port.mk>
